### ISSUE TITLE
Readme Typo

### ISSUE THREAD

**Issue by dudewad** [doowb/grunt-convert#41] opened 2015-04-24 20:55 UTC
There are extra commas in xml to json section of the readme:

  convert: {
    options: {
      explicitArray: false, <-------------------HERE
    },
    xml2json: {
        files: [
          {
            expand: true,
            cwd: 'test/fixtures/',
            src: ['*_/_.xml'],
            dest: 'tmp/result/',
            ext: '.json'
          }
        ]
    }, <-------------HERE
  }

**Comment by jonschlinkert** [comment] 2015-04-24 21:10
is this a duplicate of #40?

**Comment by dudewad** [comment] 2015-04-24 21:26
Huh... not sure how this happened. Yes, its a dupe, but with more info (note, 2 commas called out). My bad, I meant to edit and somehow created a new ticket. Sorry... haha

**Comment by jonschlinkert** [comment] 2015-04-25 10:08
no prob!

**Closed as completed by jonschlinkert** 2015-04-25 10:08 UTC
